export { default as initI18n } from './initI18n'
export { default as getDocHref } from './getDocHref'
export { default as getFileContent } from './getFileContent'
export { default as getIssueText } from './getIssueText'
export { default as getTypeTagCode } from './getTypeTagCode'
export { default as renderLanguage } from './renderLanguage'
export { default as getTitleToA } from './getTitleToA'
export { default as getCodeDemoDesc } from './getCodeDemoDesc'
export { default as getCodeDemoPrefix } from './getCodeDemoPrefix'
export * from './getTranslationConstants'
